#!/usr/bin/env bash

set -e

# Get homebrew if not installed yet
if [ ! -d "/home/linuxbrew" ]; then
    curl -s https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/homebrew-debian.sh | sudo bash -s -- auto true true
fi

export PS1=foo
source /etc/bash.bashrc

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASEDIR}" \
    --plugin-dir "${BASEDIR}/plugins/*" \
    -c "${CONFIG}" \
    "${@}"
